name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Spring Boot Image
        uses: docker/build-push-action@v5
        with:
          context: ./packages/java/procureiq-springboot
          file: ./packages/deployment/docker/Dockerfile.springboot
          push: true
          tags: ghcr.io/${{ github.repository }}/springboot-app:latest

      - name: Build and Push Next.js Image
        uses: docker/build-push-action@v5
        with:
          context: ./packages/node/procureiq-nextjs
          file: ./packages/deployment/docker/Dockerfile.nextjs
          push: true
          tags: ghcr.io/${{ github.repository }}/nextjs-app:latest
