apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  labels:
    app: springboot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: procureiq-springboot-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: procureiq-config
                  key: SPRINGBOOT_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: procureiq-config
                  key: SPRINGBOOT_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: procureiq-secrets
                  key: SPRINGBOOT_DATASOURCE_PASSWORD
            - name: OTEL_SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: procureiq-config
                  key: SPRINGBOOT_OTEL_SERVICE_NAME
            - name: OTEL_TRACES_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: procureiq-config
                  key: SPRINGBOOT_OTEL_TRACES_EXPORTER
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: procureiq-config
                  key: SPRINGBOOT_OTEL_EXPORTER_ENDPOINT
            - name: OTEL_METRICS_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: procureiq-config
                  key: SPRINGBOOT_OTEL_METRICS_EXPORTER
            - name: OTEL_LOGS_EXPORTER
              valueFrom:
                configMapKeyRef:
                  name: procureiq-config
                  key: SPRINGBOOT_OTEL_LOGS_EXPORTER
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app-service
spec:
  type: ClusterIP
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
