export const AUTH_STRINGS = {
  HEADER: {
    DEFAULT_TITLE: "Identity & Access Roles",
    DEFAULT_DESCRIPTION: "Manage user credentials, API keys, and track role assignments.",
    PORT_LABEL: "Access Port",
  },
  ACCOUNTS: {
    TITLE: "Platform User Accounts",
    DESCRIPTION: "Configure credentials and review role definitions.",
    ACTION_SUSPEND: "Suspend",
    ACTION_ACTIVATE: "Activate",
  },
  API_KEY: {
    TITLE: "System API Keys",
    DESCRIPTION: "Generate access keys for Spring Boot & Python endpoints.",
    USAGE_NOTE: "Use API Keys to authenticate external services requesting dispatching records or smart contract state details.",
    BTN_GENERATE: "Generate API Key",
    BTN_GENERATING: "Generating...",
  },
  SECURITY_NOTICE: {
    TITLE: "Security Notice",
    DEFAULT_MESSAGE: "Ensure API keys are stored securely. Never commit them to version control pipeline. Regenerate compromised keys immediately.",
  },
  LOGIN: {
    TITLE: "Platform Login",
    DESCRIPTION: "Sign in to your ProcureIQ account using your credentials.",
    SUBMIT_BTN: "Sign In",
    LABEL_USERNAME: "Username or Email",
    LABEL_PASSWORD: "Password",
    PLACEHOLDER_USERNAME: "e.g. john_doe",
    PLACEHOLDER_PASSWORD: "••••••••",
    FORGOT_PASSWORD_LINK: "Forgot your password?",
    NO_ACCOUNT_PROMPT: "Don't have an account?",
    SIGNUP_LINK: "Sign up",
  },
  SIGNUP: {
    TITLE: "Create Account",
    DESCRIPTION: "Register a new platform account to access ProcureIQ tools.",
    SUBMIT_BTN: "Create Account",
    LABEL_USERNAME: "Username",
    LABEL_EMAIL: "Email Address",
    LABEL_PASSWORD: "Password",
    LABEL_CONFIRM_PASSWORD: "Confirm Password",
    PLACEHOLDER_USERNAME: "johndoe",
    PLACEHOLDER_EMAIL: "john@procureiq.com",
    HAVE_ACCOUNT_PROMPT: "Already have an account?",
    LOGIN_LINK: "Sign in",
  },
  FORGOT_PASSWORD: {
    TITLE: "Forgot Password",
    DESCRIPTION: "Enter your account email to receive a password reset token.",
    SUBMIT_BTN: "Send Reset Link",
    LABEL_EMAIL: "Account Email",
    PLACEHOLDER_EMAIL: "registered@procureiq.com",
    REMEMBER_PASSWORD_PROMPT: "Remember your password?",
    BACK_TO_LOGIN_LINK: "Back to Sign in",
  },
  RESET_PASSWORD: {
    TITLE: "Reset Password",
    DESCRIPTION: "Enter your token and choose a new secure password.",
    SUBMIT_BTN: "Update Password",
    LABEL_TOKEN: "Reset Token",
    LABEL_NEW_PASSWORD: "New Password",
    PLACEHOLDER_TOKEN: "Paste token here...",
    BACK_TO_LOGIN_LINK: "Back to Sign in",
  },
  VERIFY_EMAIL: {
    TITLE: "Verify Email Address",
    DESCRIPTION: "Enter your email address and verification token to verify your account.",
    SUBMIT_BTN: "Verify Account Email",
    LABEL_EMAIL: "Account Email",
    LABEL_TOKEN: "Verification Token",
    PLACEHOLDER_EMAIL: "user@procureiq.com",
    PLACEHOLDER_TOKEN: "token_verify_xxx",
    BACK_TO_LOGIN_LINK: "Back to Sign in",
  },
  SAGA: {
    PROCESSING_LABEL: "Processing...",
    STEP_LABEL: "Step",
  },
  ERRORS: {
    REQUIRED_FIELDS: "All fields are required.",
    PASSWORD_MISMATCH: "Passwords do not match.",
    INVALID_CREDENTIALS: "Invalid username or password.",
    MISSING_TOKEN: "Verification token is missing or invalid.",
  },
  SUCCESS: {
    LOGIN_WELCOME: "Welcome back! Authentication successful.",
    SIGNUP_SUCCESS: "Account created successfully! Email verification link has been sent.",
    FORGOT_PASSWORD_SENT: "Password reset token sent to your email address.",
    PASSWORD_RESET_DONE: "Password updated successfully! You can now log in.",
    EMAIL_VERIFIED: "Email address verified successfully.",
  },
} as const
